# Generated by Django 5.1.6 on 2025-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('totalbeds', models.IntegerField()),
                ('bedsavailable', models.IntegerField()),
            ],
        ),
    ]
